### Classifier using Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np


In [25]:
# Local data cache
datafile = "../../data/CLEAN-DataSample-WeightHeight.csv"

In [26]:
# Read data from local file
data = pd.read_csv(datafile)
data.set_index('S.No.', inplace=True)
data.head()

,Height (cm),Weight (kg),BMI (numeric),"BMI Category = C1, C2, C3, C4"
S.No.,,,,
1,164.0,74.5,NaN,NaN
2,151.0,75.2,NaN,NaN
3,168.0,67.8,NaN,NaN
4,168.0,76.4,NaN,NaN
5,170.0,70.0,NaN,NaN


In [ ]:
# compute BMI
data["BMI (numeric)"] = data["Weight (kg)"] / ((data["Height (cm)"]/100) ** 2)

# categorize BMI
def bmi_category(bmi):
    if bmi < 18.5:
        return "C1"
    elif bmi < 25:
        return "C2"
    elif bmi < 30:
        return "C3"
    else:
        return "C4"

# get bmi categories
data['"BMI Category = C1, C2, C3, C4"'] = data["BMI (numeric)"].apply(bmi_category)

In [28]:
# get X and y
X = data ['Height (cm)']
y = data ['"BMI Category = C1, C2, C3, C4"']

# reshape and retype
X, y = np.array(X), np.array(y)
X = X.reshape(-1,1)

# train test splits
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(y)

['C3' 'C4' 'C2' 'C3' 'C2' 'C2' 'C2' 'C2' 'C2' 'C2' 'C3' 'C4' 'C2' 'C3'
 'C2' 'C2' 'C2' 'C2' 'C2' 'C2' 'C3' 'C4' 'C4' 'C3' 'C3' 'C2' 'C1' 'C3'
 'C3']


In [ ]:
# Fit to model
clf = LogisticRegression(random_state=0).fit(X, y)

In [ ]:
# predict test values
y_pred = clf.predict(X_test)

# print confusion matrix and classification report
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Example predictions
test_heights = pd.DataFrame({"Height (cm)": [50, 100, 150, 200, 250]})
print("Predicted BMI categories:", clf.predict(test_heights))

Confusion Matrix:
 [[2 0 0]
 [0 3 0]
 [1 0 0]]

Classification Report:
               precision    recall  f1-score   support

          C2       0.67      1.00      0.80         2
          C3       1.00      1.00      1.00         3
          C4       0.00      0.00      0.00         1

    accuracy                           0.83         6
   macro avg       0.56      0.67      0.60         6
weighted avg       0.72      0.83      0.77         6

Predicted BMI categories: ['C4' 'C4' 'C2' 'C3' 'C3']


c:\Users\leafr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\leafr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\leafr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo